name: Build Docker Images and Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest

    steps:

      # Checkout latest code
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Setup Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Backend
      - name: Build and Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          no-cache: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/backend:latest

      # Build and push Frontend
      - name: Build and Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          no-cache: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      # Trigger Backend Render deployment
      - name: Deploy Backend to Render
        run: |
          curl --fail --silent --show-error \
            -X POST \
            "${{ secrets.RENDER_BACKEND_DEPLOY_HOOK_URL }}"

      # Trigger Frontend Render deployment
      - name: Deploy Frontend to Render
        run: |
          curl --fail --silent --show-error \
            -X POST \
            "${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK_URL }}"